language: java
before_deploy: "gradle jar"
deploy:
  provider: releases
  api_key:
    secure: Skonfc6lFRDzP5ETjPzcvzdrzVN8MC3zqu1DR4i6u4ORGcAcmXm3oDtYyQCfxZ58L8tOb9n1Co0DDoOmokXreeCM20NE42XKf0BeJ3YEvocIwjdxLQ1CCA2gJ5x4aJWOhLlRW8lkbR3O+nVMEFoz9S8lS/5ruaWazQDNQJhKpDI=
  file: "build/libs/hue2mqtt.jar"
  skip_cleanup: true
  on:
    repo: owagner/hue2mqtt
    tags: true
    all_branches: true
